name: Build
on: [push, pull_request]

jobs:
  buildBizHawk:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'CemuStub-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '505'
        path: 'RTCV'
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Restore Nuget packages in CemuStub
      run: nuget restore '.\CemuStub-Vanguard\'
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild '.\CemuStub-Vanguard\'
